### ISSUE TITLE
DB::Exception: Empty query when executing is_alive() through chproxy

### ISSUE THREAD

**Issue by borisrozumnuk** [maximdanilchenko/aiochclient#24]
code from aiochclient
```
async def is_alive(self) -> bool:
    """Checks if connection is Ok.

    Usage:

    .. code-block:: python

        assert await client.is_alive()

    :return: True if connection Ok. False instead.
    """
    async with self._session.get(
        url=self.url
    ) as resp:  # type: client.ClientResponse
        return resp.status == 200
```

Clickhouse exception stacktrace
```
2020.03.06 14:11:56.086811 [ 393 ] {15F9BC3CD4B6DFAF} <Error> HTTPHandler: Code: 62, e.displayText() = DB::Exception: Empty query, Stack trace:
0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x30) [0x7f0ef70]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x25) [0x3c53485]
2. /usr/bin/clickhouse-server() [0x3aa1529]
3. /usr/bin/clickhouse-server() [0x6eac2b8]
4. /usr/bin/clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)+0x1aa) [0x6eada9a]
5. /usr/bin/clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x1a5e) [0x3ca07fe]
6. /usr/bin/clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x45a) [0x3ca2b5a]
7. /usr/bin/clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x2a9) [0x79c0c59]
8. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0x10) [0x79bba30]
9. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xed) [0x79bc14d]
10. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x81) [0x807ffc1]
11. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x3c) [0x807dd6c]
12. /usr/bin/clickhouse-server() [0xba53c60]
13. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fa138b2c6ba]
14. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fa13835541d]
 (version 19.13.4.32 (official build))
```

chproxy config:

```
server:
  http:
      listen_addr: ":<listen-address>"
      allowed_networks: [<networks-list>]
users:
  - name: "readonly"
    allowed_networks: [<networks-list>]
    to_cluster: "clickhouse"
    to_user: "readonly"
    max_concurrent_queries: 6
    max_execution_time: 1m
    password: "$READONLY_PASS"

  - name: "default"
    allowed_networks: [<networks-list>]
    to_cluster: "clickhouse"
    to_user: "default"
    max_concurrent_queries: 6
    max_execution_time: 1m
    password: "$DEFAULT_PASS"

clusters:
  - name: "clickhouse"
    nodes: [
      "$CH_NODES"
    ]
    users:
    - name: "readonly"
      password: "$READONLY_PASS"
    - name: "default"
      password: "$DEFAULT_PASS"
```
```
